[package]
name = "chip-8-emulator"
version = "1.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
minifb = "0.25.0"
rand = "0.8.5"

