[package]
name = "chip-8-emulator"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
minifb = "0.25.0"
rand = "0.8.5"

