[package]
name = "chip8"
version = "1.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
eframe = "0.32.3"
egui = "0.32.3"
raplay = "0.4.3"
